# Generated by Django 5.1.7 on 2025-04-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_contact_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('student_pref_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pref_location', models.CharField(max_length=100)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.industry')),
                ('student_pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentpreference')),
            ],
            options={
                'unique_together': {('student_pref', 'industry')},
            },
        ),
        migrations.CreateModel(
            name='DesiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
                ('student_pref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentpreference')),
            ],
            options={
                'unique_together': {('student_pref', 'skill')},
            },
        ),
    ]
