# Generated by Django 5.1.7 on 2025-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_of_study', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('student_contact_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
