# Generated by Django 5.1.7 on 2025-04-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('plot_no', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('street', 'plot_no')},
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.industry')),
            ],
        ),
    ]
