# Generated by Django 5.1.7 on 2025-04-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_industry_location_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
    ]
