# Generated by Django 5.1.7 on 2025-04-08 10:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_industry_location_organisation_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='logbook_id',
            field=models.CharField(default=users.models.generate_random_logbook_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
