# Generated by Django 5.1.7 on 2025-04-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPreference',
            fields=[
                ('pref_id', models.AutoField(primary_key=True, serialize=False)),
                ('pref_education_level', models.CharField(max_length=100)),
                ('positions_available', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredField',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_fields', to='users.organisationpreference')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='users.organisationpreference')),
            ],
        ),
    ]
