# Generated by Django 5.1.7 on 2025-04-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organisationpreference_preferredfield_requiredskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpreference',
            name='organisation',
            field=models.ForeignKey(db_column='organisation_id', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.organisation'),
        ),
    ]
